import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { DossierMedical } from '../interfaces/dossier-medical';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class DossierMedicalService {
  private dossiersMedicaux: DossierMedical[] = [
    {
      identification: {
        nom: 'NomPatient-1',
        prenom: 'Prenom-Patient-1',
        dateDeNaissance: '01/11/2000',
        lieuDeNaissance: 'Douala',
        ethnie: 'inconnue',
        profession: 'Mecanicien',
        lieuDeResidence: "Av. de l' independance 01, Yaounde",
        personneAcontacter: 'Max Mustermann',
      },
      antecedents: {
        medicaux: 'Néant',
        chirurgicaux: 'Néant',
        immunoAllergics: 'Néant',
        toxicologics: 'Néant',
        familiaux: 'Néant',
      },
      histoireMaladie: 'Néant',
      examenPhysic: 'Néant',
      hypotheseDiagnostic: 'Néant',
      bilanRadiologic: 'Néant',
      bilanBiologic: 'Néant',
      diagnosticRetenu: 'Néant',
      traitement: 'Néant',
    },
    {
      identification: {
        nom: 'NomPatient-2',
        prenom: 'Prenom-Patient-2',
        dateDeNaissance: '01/11/2000',
        lieuDeNaissance: 'Douala',
        ethnie: 'inconnue',
        profession: 'Mecanicien',
        lieuDeResidence: "Av. de l' independance 01, Yaounde",
        personneAcontacter: 'Max Mustermann',
      },
      antecedents: {
        medicaux: 'Néant',
        chirurgicaux: 'Néant',
        immunoAllergics: 'Néant',
        toxicologics: 'Néant',
        familiaux: 'Néant',
      },
      histoireMaladie: 'Néant',
      examenPhysic: 'Néant',
      hypotheseDiagnostic: 'Néant',
      bilanRadiologic: 'Néant',
      bilanBiologic: 'Néant',
      diagnosticRetenu: 'Néant',
      traitement: 'Néant',
    },
    {
      identification: {
        nom: 'NomPatient-3',
        prenom: 'Prenom-Patient-3',
        dateDeNaissance: '01/11/2000',
        lieuDeNaissance: 'Douala',
        ethnie: 'inconnue',
        profession: 'Mecanicien',
        lieuDeResidence: "Av. de l' independance 01, Yaounde",
        personneAcontacter: 'Max Mustermann',
      },
      antecedents: {
        medicaux: 'Néant',
        chirurgicaux: 'Néant',
        immunoAllergics: 'Néant',
        toxicologics: 'Néant',
        familiaux: 'Néant',
      },
      histoireMaladie: 'Néant',
      examenPhysic: 'Néant',
      hypotheseDiagnostic: 'Néant',
      bilanRadiologic: 'Néant',
      bilanBiologic: 'Néant',
      diagnosticRetenu: 'Néant',
      traitement: 'Néant',
    },
    {
      identification: {
        nom: 'NomPatient-4',
        prenom: 'Prenom-Patient-4',
        dateDeNaissance: '01/11/2000',
        lieuDeNaissance: 'Douala',
        ethnie: 'inconnue',
        profession: 'Mecanicien',
        lieuDeResidence: "Av. de l' independance 01, Yaounde",
        personneAcontacter: 'Max Mustermann',
      },
      antecedents: {
        medicaux: 'Néant',
        chirurgicaux: 'Néant',
        immunoAllergics: 'Néant',
        toxicologics: 'Néant',
        familiaux: 'Néant',
      },
      histoireMaladie: 'Néant',
      examenPhysic: 'Néant',
      hypotheseDiagnostic: 'Néant',
      bilanRadiologic: 'Néant',
      bilanBiologic: 'Néant',
      diagnosticRetenu: 'Néant',
      traitement: 'Néant',
    },
    {
      identification: {
        nom: 'NomPatient-5',
        prenom: 'Prenom-Patient-5',
        dateDeNaissance: '01/11/2000',
        lieuDeNaissance: 'Douala',
        ethnie: 'inconnue',
        profession: 'Mecanicien',
        lieuDeResidence: "Av. de l' independance 01, Yaounde",
        personneAcontacter: 'Max Mustermann',
      },
      antecedents: {
        medicaux: 'Néant',
        chirurgicaux: 'Néant',
        immunoAllergics: 'Néant',
        toxicologics: 'Néant',
        familiaux: 'Néant',
      },
      histoireMaladie: 'Néant',
      examenPhysic: 'Néant',
      hypotheseDiagnostic: 'Néant',
      bilanRadiologic: 'Néant',
      bilanBiologic: 'Néant',
      diagnosticRetenu: 'Néant',
      traitement: 'Néant',
    },
    {
      identification: {
        nom: 'NomPatient-6',
        prenom: 'Prenom-Patient-6',
        dateDeNaissance: '01/11/2000',
        lieuDeNaissance: 'Douala',
        ethnie: 'inconnue',
        profession: 'Mecanicien',
        lieuDeResidence: "Av. de l' independance 01, Yaounde",
        personneAcontacter: 'Max Mustermann',
      },
      antecedents: {
        medicaux: 'Néant',
        chirurgicaux: 'Néant',
        immunoAllergics: 'Néant',
        toxicologics: 'Néant',
        familiaux: 'Néant',
      },
      histoireMaladie: 'Néant',
      examenPhysic: 'Néant',
      hypotheseDiagnostic: 'Néant',
      bilanRadiologic: 'Néant',
      bilanBiologic: 'Néant',
      diagnosticRetenu: 'Néant',
      traitement: 'Néant',
    },
    {
      identification: {
        nom: 'NomPatient-7',
        prenom: 'Prenom-Patient-7',
        dateDeNaissance: '01/11/2000',
        lieuDeNaissance: 'Douala',
        ethnie: 'inconnue',
        profession: 'Mecanicien',
        lieuDeResidence: "Av. de l' independance 01, Yaounde",
        personneAcontacter: 'Max Mustermann',
      },
      antecedents: {
        medicaux: 'Néant',
        chirurgicaux: 'Néant',
        immunoAllergics: 'Néant',
        toxicologics: 'Néant',
        familiaux: 'Néant',
      },
      histoireMaladie: 'Néant',
      examenPhysic: 'Néant',
      hypotheseDiagnostic: 'Néant',
      bilanRadiologic: 'Néant',
      bilanBiologic: 'Néant',
      diagnosticRetenu: 'Néant',
      traitement: 'Néant',
    },
  ];

  constructor(private http: HttpClient) {}

  getDossiersMedicaux(): Observable<DossierMedical[]> {
    return of(this.dossiersMedicaux);
  }
}
